[2025-06-19T02:18:19.985-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-19T02:18:19.993-0400] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.upload_to_s3 manual__2025-06-19T06:08:15.574055+00:00 [queued]>
[2025-06-19T02:18:19.997-0400] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.upload_to_s3 manual__2025-06-19T06:08:15.574055+00:00 [queued]>
[2025-06-19T02:18:19.997-0400] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-19T02:18:20.009-0400] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): upload_to_s3> on 2025-06-19 06:08:15.574055+00:00
[2025-06-19T02:18:20.013-0400] {standard_task_runner.py:72} INFO - Started process 8192 to run task
[2025-06-19T02:18:20.018-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'covid_data_pipeline', 'upload_to_s3', 'manual__2025-06-19T06:08:15.574055+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpbvgyuqfz']
[2025-06-19T02:18:20.019-0400] {standard_task_runner.py:105} INFO - Job 8: Subtask upload_to_s3
[2025-06-19T02:18:20.071-0400] {task_command.py:467} INFO - Running <TaskInstance: covid_data_pipeline.upload_to_s3 manual__2025-06-19T06:08:15.574055+00:00 [running]> on host manasajagati.localdomain
[2025-06-19T02:18:20.164-0400] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manasa' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T06:08:15.574055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T06:08:15.574055+00:00'
[2025-06-19T02:18:20.168-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-19T02:18:20.168-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-19T02:18:20.169-0400] {logging_mixin.py:190} INFO - Current task name:upload_to_s3 state:running start_date:2025-06-19 06:18:19.993793+00:00
[2025-06-19T02:18:20.169-0400] {logging_mixin.py:190} INFO - Dag name:covid_data_pipeline and current dag run status:running
[2025-06-19T02:18:20.170-0400] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-19T02:18:20.171-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-19T02:18:20.173-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/covid_data_pipeline/scripts/upload_to_s3.py']
[2025-06-19T02:18:20.190-0400] {subprocess.py:99} INFO - Output:
[2025-06-19T02:18:20.205-0400] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-19T02:18:20.205-0400] {subprocess.py:106} INFO -   File "/home/jagat/covid_data_pipeline/scripts/upload_to_s3.py", line 1, in <module>
[2025-06-19T02:18:20.205-0400] {subprocess.py:106} INFO -     import boto3
[2025-06-19T02:18:20.206-0400] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'boto3'
[2025-06-19T02:18:20.207-0400] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-19T02:18:20.213-0400] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:18:20.224-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-19T02:18:20.224-0400] {logging_mixin.py:190} INFO - Task start:2025-06-19 06:18:19.993793+00:00 end:2025-06-19 06:18:20.223382+00:00 duration:0.229589
[2025-06-19T02:18:20.225-0400] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): upload_to_s3> dag:<DAG: covid_data_pipeline> dagrun:<DagRun covid_data_pipeline @ 2025-06-19 06:08:15.574055+00:00: manual__2025-06-19T06:08:15.574055+00:00, state:running, queued_at: 2025-06-19 06:18:13.033795+00:00. externally triggered: True>
[2025-06-19T02:18:20.225-0400] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:18:20.225-0400] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_pipeline, task_id=upload_to_s3, run_id=manual__2025-06-19T06:08:15.574055+00:00, execution_date=20250619T060815, start_date=20250619T061819, end_date=20250619T061820
[2025-06-19T02:18:20.241-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-19T02:18:20.242-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 8192)
Traceback (most recent call last):
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:18:20.286-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-19T02:18:20.319-0400] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T02:18:20.320-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
