[2025-06-19T02:07:42.507-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-19T02:07:42.512-0400] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.extract_covid_data scheduled__2025-06-18T00:00:00+00:00 [queued]>
[2025-06-19T02:07:42.515-0400] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.extract_covid_data scheduled__2025-06-18T00:00:00+00:00 [queued]>
[2025-06-19T02:07:42.515-0400] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-06-19T02:07:42.526-0400] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): extract_covid_data> on 2025-06-18 00:00:00+00:00
[2025-06-19T02:07:42.528-0400] {standard_task_runner.py:72} INFO - Started process 6779 to run task
[2025-06-19T02:07:42.533-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'covid_data_pipeline', 'extract_covid_data', 'scheduled__2025-06-18T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/covid_pipeline_dag.py', '--cfg-path', '/tmp/tmpz_g0ten_']
[2025-06-19T02:07:42.534-0400] {standard_task_runner.py:105} INFO - Job 3: Subtask extract_covid_data
[2025-06-19T02:07:42.568-0400] {task_command.py:467} INFO - Running <TaskInstance: covid_data_pipeline.extract_covid_data scheduled__2025-06-18T00:00:00+00:00 [running]> on host manasajagati.localdomain
[2025-06-19T02:07:42.607-0400] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manasa' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_covid_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-18T00:00:00+00:00'
[2025-06-19T02:07:42.608-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-19T02:07:42.608-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-19T02:07:42.608-0400] {logging_mixin.py:190} INFO - Current task name:extract_covid_data state:running start_date:2025-06-19 06:07:42.513127+00:00
[2025-06-19T02:07:42.608-0400] {logging_mixin.py:190} INFO - Dag name:covid_data_pipeline and current dag run status:running
[2025-06-19T02:07:42.608-0400] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-19T02:07:42.610-0400] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-19T02:07:42.610-0400] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ~/covid_data_pipeline/scripts/extract_covid_data.py']
[2025-06-19T02:07:42.615-0400] {subprocess.py:99} INFO - Output:
[2025-06-19T02:07:42.698-0400] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-06-19T02:07:42.699-0400] {subprocess.py:106} INFO -   File "/home/jagat/covid_data_pipeline/scripts/extract_covid_data.py", line 2, in <module>
[2025-06-19T02:07:42.699-0400] {subprocess.py:106} INFO -     import pandas as pd
[2025-06-19T02:07:42.699-0400] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'pandas'
[2025-06-19T02:07:42.708-0400] {subprocess.py:110} INFO - Command exited with return code 1
[2025-06-19T02:07:42.713-0400] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:07:42.718-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-19T02:07:42.718-0400] {logging_mixin.py:190} INFO - Task start:2025-06-19 06:07:42.513127+00:00 end:2025-06-19 06:07:42.717794+00:00 duration:0.204667
[2025-06-19T02:07:42.718-0400] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): extract_covid_data> dag:<DAG: covid_data_pipeline> dagrun:<DagRun covid_data_pipeline @ 2025-06-18 00:00:00+00:00: scheduled__2025-06-18T00:00:00+00:00, state:running, queued_at: 2025-06-19 06:07:40.677336+00:00. externally triggered: False>
[2025-06-19T02:07:42.718-0400] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:07:42.718-0400] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_pipeline, task_id=extract_covid_data, run_id=scheduled__2025-06-18T00:00:00+00:00, execution_date=20250618T000000, start_date=20250619T060742, end_date=20250619T060742
[2025-06-19T02:07:42.729-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-19T02:07:42.729-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task extract_covid_data (Bash command failed. The command returned a non-zero exit code 1.; 6779)
Traceback (most recent call last):
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jagat/covid_data_pipeline/airflow_env_linux/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-19T02:07:42.758-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-19T02:07:42.777-0400] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T02:07:42.778-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
